<!--
left-navigation 마크업 및 클래스 추가/수정
//-->
<div class="left-navigation flex flex-wrap ">
  <div class="flex-wrap clinic-name">펜1</div>
  <div class="ver-scroll flex-fill">
    <div class="menu depth-0">
      <div class="menu-item selected">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-home"></i>현황판 (홈)</span></div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-calender"></i>예약 캘린더</span></div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-consult"></i>상담문의 관리</span><i class="zmdi c-primary flex-wrap zmdi-chevron-up"></i></div>
        <div class="menu depth-1">
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">상담문의</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">담당자 배정</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">연동설정</span></div>
          </div>
        </div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-msg"></i>문자 관리</span><i class="zmdi c-primary flex-wrap zmdi-chevron-up"></i></div>
        <div class="menu depth-1">
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">문자 전송</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">문자 충전</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">전송내역 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">충전내역 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">문자코드 설정</span></div>
          </div>
        </div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-inq"></i>조회</span><i class="zmdi c-primary flex-wrap zmdi-chevron-up"></i></div>
        <div class="menu depth-1">
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">고객 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">예약 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">상담 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">진료 조회</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">수납 조회</span></div>
          </div>
        </div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-stat"></i>통계</span></div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-setting"></i>환경 설정</span><i class="zmdi c-primary flex-wrap zmdi-chevron-up"></i></div>
        <div class="menu depth-1">
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">고객코드 설정</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">예약캘린더 설정</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">상담코드 설정</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">수납코드 설정</span></div>
          </div>
        </div>
      </div>
      <div class="menu-item ">
        <div class="title flex-row"><span class="text flex-fill"><i class="ico ic-hospital"></i>병원 관리</span><i class="zmdi c-primary flex-wrap zmdi-chevron-up"></i></div>
        <div class="menu depth-1">
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">조직 관리</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">직원 관리</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">병원 정보</span></div>
          </div>
          <div class="menu-item ">
            <div class="title flex-row"><span class="text flex-fill">펜차트 샘플함</span></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
left-navigation 마크업 및 클래스 수정
//-->
