<meta charset="utf-8">
<link rel="icon" href="/favicon.png">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#000000">
<meta name="description" content="Web site created using create-react-app">
<link rel="apple-touch-icon" href="/logo192.png">
<link rel="manifest" href="/manifest.json">
<title>CRM - 펜1</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<link href="/crm/static/css/base.css" rel="stylesheet">
<link href="/crm/static/css/main.css" rel="stylesheet">
<link href="/crm/static/css/ui.css" rel="stylesheet">
