<!-- header-bar -->
<div class="header-bar flex-row flex-between ui-header"> <!-- add class=ui-header //-->
  <div class="header-items left flex-wrap">
    <h1 class="title">바비톡 성형외과</h1>
    <button class="btn btn-close"><span class="a11y">사이드 닫기/열기</span></button>
  </div>
  <div class="flex-row items-center flex-between flex-fill">
    <div class="customer-search-bar flex-row items-center">
      <input placeholder="고객명, 차트번호, 전화번호, 주민번호" class="flex-fill" value="">
      <div class="buttons flex-row flex-wrap">
        <button class="btn btn-accent m-l-8">검색</button>
        <button class="btn btn-accent m-l-8">고객등록</button>
      </div>
    </div>
    <div class="header-items right">
      <div class="me _sched">
        <button class="btn btn-sched"><span class="alram"></span>부재일정확인</button>
      </div>
      <div class="me _info">
        <p>park</p>
        <p class="email"><a href="mailto:test1@gmail.com">test1@gmail.com</a></p>
      </div>

      <!--
      디자인확인필요
      <i class="zmdi zmdi-font"></i>
      <i class="zmdi zmdi-power"></i>
      -->
    </div>
  </div>
</div>
<!--// header-bar -->
