<div class="header-bar flex-row flex-between ui-header">
  <div class="header-items left flex-wrap"><i class="zmdi zmdi-close"></i>
    <div class="flex-wrap cursor-pointer">현황판 (홈)</div>
  </div>
  <div class="flex-row items-center flex-between flex-fill">
    <div class="customer-search-bar flex-row items-center"><input placeholder="고객명, 차트번호, 전화번호, 주민번호" class="flex-fill" value="">
      <div class="buttons flex-row flex-wrap"><button class="btn btn-accent btn-sm m-l-8">조회</button><button class="btn btn-accent btn-sm m-l-8">신규고객등록</button></div>
    </div>
    <div class="header-items right"><button class="btn btn-accent btn-sm m-r-8">부재일정확인</button>
      <div class="me m-r-16">park (test1@gmail.com)</div><i class="zmdi zmdi-font"></i><i class="zmdi zmdi-power"></i>
    </div>
  </div>
</div>
